TX=$1
echo "Getting raw transaction..."
HEX=$(curl -sSL "https://mempool.space/api/tx/$TX/hex" | tr -cd '[:xdigit:]')
echo "Broadcasting via mempool.space node..."
curl -X POST -sSLd "$HEX" -w "\n" "https://mempool.space/api/tx"
echo "Broadcasting  via blockstream.info node..."
curl -X POST -sSLd "$HEX" -w "\n" "https://blockstream.info/api/tx"
echo "Broadcasting via blockchain.info node..."
curl -X POST -sSLd "tx=$HEX" -w "\n" "https://blockchain.info/pushtx"
echo "Broadcasting via viabtc.com node..."
curl -X POST -H 'Content-Type: application/json' -sSLd "{\"coin\":\"BTC\",\"raw_tx\":\"$HEX\"}" -w "\n" "https://www.viabtc.com/res/tools/broadcast"
echo "Broadcasting via bitaps.com..."
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -sSLd "{\"jsonrpc\":\"1.0\",\"id\":\"1\",\"method\":\"sendrawtransaction\",\"params\":[\"$HEX\"]}" -w "\n" "https://api.bitaps.com/btc/native/"
echo "Broadcasting via btc.network..."
curl -X POST -H 'Content-Type: application/json' -sSLd "{\"data\":\"$TX\"}" -w "\n" "https://api.btc.network/broadcast"
echo "Broadcasting via btc.com..."
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -sSLd "rawhex=$HEX" -w "\n" "https://btc.com/service/tx/publish"
echo "Broadcasting via coinb.in..."
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -sSLd "rawtx=$HEX" -w "\n" "https://coinb.in/api/?uid=1&key=12345678901234567890123456789012&setmodule=bitcoin&request=sendrawtransaction"
